apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-project-deployment
  labels:
    app: devops-demo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo-project
  template:
    metadata:
      labels:
        app: devops-demo-project
    spec:
      containers:
        - name: devops-demo-project
          image: devops-demo:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-demo-project-service
spec:
  type: NodePort
  selector:
    app: devops-demo-project
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30000