apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-project-deployment
  namespace: devops-demo
  labels:
    app: devops-demo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo-project
  template:
    metadata:
      labels:
        app: devops-demo-project
    spec:
      containers:
        - name: devops-demo-project
          image: devops-demo
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: devops-demo-project-service
  namespace: devops-demo
spec:
  type: NodePort
  selector:
    app: devops-demo-project
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30001